// Package config reads and writes ~/.config/skills-mcp/registry.toml.
// Mirrors src/skills_mcp/config.py exactly so the Python MCP server and the
// Go CLI agree on registry identity.
package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// EnvVar is the override knob; SKILLS_REGISTRY=owner/repo[@branch].
const EnvVar = "SKILLS_REGISTRY"

// Config holds the resolved registry details.
type Config struct {
	Repo          string // "owner/repo"
	DefaultBranch string // "main" by default
}

// Owner returns the GitHub owner portion of Repo.
func (c Config) Owner() string {
	if i := strings.Index(c.Repo, "/"); i >= 0 {
		return c.Repo[:i]
	}
	return c.Repo
}

// Name returns the repo name portion of Repo.
func (c Config) Name() string {
	if i := strings.Index(c.Repo, "/"); i >= 0 {
		return c.Repo[i+1:]
	}
	return c.Repo
}

// ErrMissing is returned when no config exists and no env var is set.
var ErrMissing = errors.New("no registry configured (set SKILLS_REGISTRY=owner/repo or run `skills-registry`)")

// Path returns the on-disk location of registry.toml, honoring XDG_CONFIG_HOME.
func Path() string {
	if base := os.Getenv("XDG_CONFIG_HOME"); base != "" {
		return filepath.Join(base, "skills-mcp", "registry.toml")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "skills-mcp", "registry.toml")
}

// Load resolves the active config. Env var wins over the file.
func Load() (Config, error) {
	if v := strings.TrimSpace(os.Getenv(EnvVar)); v != "" {
		repo, branch := parseEnvValue(v)
		if err := validate(repo); err != nil {
			return Config{}, err
		}
		return Config{Repo: repo, DefaultBranch: branch}, nil
	}
	path := Path()
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return Config{}, ErrMissing
		}
		return Config{}, fmt.Errorf("read %s: %w", path, err)
	}
	cfg, err := parseTOML(string(data))
	if err != nil {
		return Config{}, fmt.Errorf("parse %s: %w", path, err)
	}
	if err := validate(cfg.Repo); err != nil {
		return Config{}, err
	}
	return cfg, nil
}

// Save writes the config to disk, creating parent dirs.
func Save(cfg Config) (string, error) {
	if err := validate(cfg.Repo); err != nil {
		return "", err
	}
	if cfg.DefaultBranch == "" {
		cfg.DefaultBranch = "main"
	}
	path := Path()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	body := "# Auto-generated by `skills-registry bootstrap`. Edit `repo` to point at a different registry.\n" +
		"[registry]\n" +
		fmt.Sprintf("repo = %q\n", cfg.Repo) +
		fmt.Sprintf("default_branch = %q\n", cfg.DefaultBranch)
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func parseEnvValue(v string) (string, string) {
	repo := v
	branch := "main"
	if i := strings.Index(v, "@"); i >= 0 {
		repo = strings.TrimSpace(v[:i])
		if alt := strings.TrimSpace(v[i+1:]); alt != "" {
			branch = alt
		}
	}
	return repo, branch
}

func validate(repo string) error {
	if repo == "" {
		return fmt.Errorf("invalid registry repo: empty")
	}
	parts := strings.Split(repo, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return fmt.Errorf("invalid registry repo %q (expected owner/repo)", repo)
	}
	return nil
}

// parseTOML hand-parses our one-section file. We avoid pulling in a TOML
// dependency for three keys.
func parseTOML(text string) (Config, error) {
	cfg := Config{DefaultBranch: "main"}
	inSection := false
	for _, raw := range strings.Split(text, "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			inSection = line == "[registry]"
			continue
		}
		if !inSection {
			continue
		}
		key, value, ok := splitKV(line)
		if !ok {
			continue
		}
		switch key {
		case "repo":
			cfg.Repo = value
		case "default_branch":
			if value != "" {
				cfg.DefaultBranch = value
			}
		}
	}
	if cfg.Repo == "" {
		return Config{}, fmt.Errorf("missing [registry].repo")
	}
	return cfg, nil
}

func splitKV(line string) (string, string, bool) {
	i := strings.Index(line, "=")
	if i < 0 {
		return "", "", false
	}
	key := strings.TrimSpace(line[:i])
	val := strings.TrimSpace(line[i+1:])
	val = strings.Trim(val, "\"'")
	return key, val, true
}
