import Foundation

/// Read/write `~/.config/skills-mcp/registry.toml`, the file the Go CLI and
/// Python server both read for registry identity. Keeping the macOS app on the
/// same file means the app, the CLI, and the hosted MCP all agree on which
/// repo is "the registry". Mirrors `cli/internal/config/config.go`.
public struct RegistryConfig: Equatable, Sendable {
    public var repo: String          // "owner/repo"
    public var defaultBranch: String // "main" by default

    public init(repo: String, defaultBranch: String = "main") {
        self.repo = repo
        self.defaultBranch = defaultBranch.isEmpty ? "main" : defaultBranch
    }

    public var ref: RepoRef? { RepoRef(fullName: repo) }

    public enum ConfigError: Error, LocalizedError {
        case missing
        case invalidRepo(String)

        public var errorDescription: String? {
            switch self {
            case .missing:
                return "No registry configured yet."
            case .invalidRepo(let r):
                return "Invalid registry repo \"\(r)\" (expected owner/repo)."
            }
        }
    }

    /// On-disk location, honoring XDG_CONFIG_HOME.
    public static var path: URL {
        let env = ProcessInfo.processInfo.environment
        if let base = env["XDG_CONFIG_HOME"], !base.isEmpty {
            return URL(fileURLWithPath: base)
                .appendingPathComponent("skills-mcp/registry.toml")
        }
        return FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".config/skills-mcp/registry.toml")
    }

    /// Resolve the active config. The `SKILLS_REGISTRY` env override wins over
    /// the file, matching the CLI.
    public static func load() throws -> RegistryConfig {
        let env = ProcessInfo.processInfo.environment
        if let v = env["SKILLS_REGISTRY"]?.trimmingCharacters(in: .whitespaces), !v.isEmpty {
            let (repo, branch) = parseEnvValue(v)
            try validate(repo)
            return RegistryConfig(repo: repo, defaultBranch: branch)
        }
        let url = path
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw ConfigError.missing
        }
        let data = try String(contentsOf: url, encoding: .utf8)
        let cfg = try parseTOML(data)
        try validate(cfg.repo)
        return cfg
    }

    /// Best-effort load that returns nil when no config exists (or is invalid).
    public static func loadOptional() -> RegistryConfig? {
        try? load()
    }

    @discardableResult
    public func save() throws -> URL {
        try RegistryConfig.validate(repo)
        let url = RegistryConfig.path
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        let body = """
        # Auto-generated by Skills Registry. Edit `repo` to point at a different registry.
        [registry]
        repo = "\(repo)"
        default_branch = "\(defaultBranch.isEmpty ? "main" : defaultBranch)"

        """
        try body.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    // MARK: - parsing

    static func parseEnvValue(_ v: String) -> (String, String) {
        if let at = v.firstIndex(of: "@") {
            let repo = String(v[..<at]).trimmingCharacters(in: .whitespaces)
            let branch = String(v[v.index(after: at)...]).trimmingCharacters(in: .whitespaces)
            return (repo, branch.isEmpty ? "main" : branch)
        }
        return (v.trimmingCharacters(in: .whitespaces), "main")
    }

    static func validate(_ repo: String) throws {
        if repo.isEmpty { throw ConfigError.invalidRepo("") }
        let parts = repo.split(separator: "/", omittingEmptySubsequences: false)
        guard parts.count == 2, !parts[0].isEmpty, !parts[1].isEmpty else {
            throw ConfigError.invalidRepo(repo)
        }
    }

    /// Hand-parse our one-section file (avoids a TOML dependency for 2 keys).
    static func parseTOML(_ text: String) throws -> RegistryConfig {
        var repo = ""
        var branch = "main"
        var inSection = false
        for rawLine in text.components(separatedBy: "\n") {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            if line.isEmpty || line.hasPrefix("#") { continue }
            if line.hasPrefix("[") && line.hasSuffix("]") {
                inSection = (line == "[registry]")
                continue
            }
            if !inSection { continue }
            guard let eq = line.firstIndex(of: "=") else { continue }
            let key = String(line[..<eq]).trimmingCharacters(in: .whitespaces)
            var val = String(line[line.index(after: eq)...]).trimmingCharacters(in: .whitespaces)
            val = val.trimmingCharacters(in: CharacterSet(charactersIn: "\"'"))
            switch key {
            case "repo": repo = val
            case "default_branch": if !val.isEmpty { branch = val }
            default: break
            }
        }
        if repo.isEmpty { throw ConfigError.invalidRepo("") }
        return RegistryConfig(repo: repo, defaultBranch: branch)
    }
}
