"""Read/write ``~/.config/skills-mcp/registry.toml``.

Tiny TOML usage — one section, three keys — so we hand-roll write to avoid
adding ``tomli-w`` as a runtime dependency. ``tomllib`` is in stdlib from
3.11; for 3.10 we hand-parse the same single section.
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from pathlib import Path

if sys.version_info >= (3, 11):
	import tomllib
else:  # pragma: no cover - exercised only on 3.10
	tomllib = None  # type: ignore[assignment]


CONFIG_ENV = "SKILLS_REGISTRY"


def config_path() -> Path:
	"""Standard config file path. Respects ``XDG_CONFIG_HOME``."""
	base = os.environ.get("XDG_CONFIG_HOME")
	root = Path(base).expanduser() if base else Path.home() / ".config"
	return root / "skills-mcp" / "registry.toml"


@dataclass(frozen=True)
class RegistryConfig:
	"""Resolved registry connection details."""

	repo: str  # "owner/repo"
	default_branch: str = "main"


class ConfigError(RuntimeError):
	"""Raised when the registry config is missing or malformed."""


def load() -> RegistryConfig:
	"""Resolve the active registry config.

	Resolution order:
	1. ``SKILLS_REGISTRY=owner/repo`` env var (optionally ``owner/repo@branch``)
	2. ``~/.config/skills-mcp/registry.toml``

	Raises :class:`ConfigError` with actionable text on failure.
	"""
	env_val = os.environ.get(CONFIG_ENV, "").strip()
	if env_val:
		repo, _, branch = env_val.partition("@")
		repo = repo.strip()
		branch = branch.strip() or "main"
		_validate_repo(repo)
		return RegistryConfig(repo=repo, default_branch=branch)

	path = config_path()
	if not path.is_file():
		raise ConfigError(
			f"No registry configured. Set {CONFIG_ENV}=owner/repo or run `skills-registry init`.\n"
			f"(Expected config at {path}.)"
		)
	return _parse_toml(path)


def save(cfg: RegistryConfig) -> Path:
	"""Write ``cfg`` to disk. Creates parent dirs. Returns the path written."""
	path = config_path()
	path.parent.mkdir(parents=True, exist_ok=True)
	body = (
		"# Auto-generated by `skills-registry init`. Edit `repo` to point at a different registry.\n"
		"[registry]\n"
		f'repo = "{cfg.repo}"\n'
		f'default_branch = "{cfg.default_branch}"\n'
	)
	path.write_text(body, encoding="utf-8")
	return path


def _validate_repo(repo: str) -> None:
	if "/" not in repo or repo.count("/") > 1:
		raise ConfigError(f"Invalid registry repo {repo!r}. Expected `owner/repo`.")
	owner, name = repo.split("/", 1)
	if not owner or not name:
		raise ConfigError(f"Invalid registry repo {repo!r}. Expected `owner/repo`.")


def _parse_toml(path: Path) -> RegistryConfig:
	text = path.read_text(encoding="utf-8")
	if tomllib is not None:
		try:
			data = tomllib.loads(text)
		except tomllib.TOMLDecodeError as exc:
			raise ConfigError(f"Could not parse {path}: {exc}") from exc
		section = data.get("registry") or {}
		repo = str(section.get("repo", "")).strip()
		branch = str(section.get("default_branch", "main")).strip() or "main"
	else:
		# 3.10 fallback — only one flat section, key=value.
		repo, branch = _parse_toml_minimal(text)
	if not repo:
		raise ConfigError(
			f"{path} has no [registry].repo. Re-run `skills-registry init` or fix the file."
		)
	_validate_repo(repo)
	return RegistryConfig(repo=repo, default_branch=branch)


def _parse_toml_minimal(text: str) -> tuple[str, str]:
	"""Parse a one-section TOML for Python 3.10. Tolerates comments/blank lines."""
	in_section = False
	repo = ""
	branch = "main"
	for raw in text.splitlines():
		line = raw.strip()
		if not line or line.startswith("#"):
			continue
		if line.startswith("[") and line.endswith("]"):
			in_section = line == "[registry]"
			continue
		if not in_section or "=" not in line:
			continue
		key, _, value = line.partition("=")
		val = value.strip().strip('"').strip("'")
		if key.strip() == "repo":
			repo = val
		elif key.strip() == "default_branch":
			branch = val or "main"
	return repo, branch
